name: Deploy to WordPress.org
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Deploy
              uses: yukihiko-shinoda/action-deploy-wordpress-plugin@v2
              env:
                  SVN_REPOSITORY_URL: ${{ secrets.SVN_URL }}
                  SVN_USER_NAME: ${{ secrets.SVN_USERNAME }}
                  SVN_USER_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  EXCLUDE: "/dist/, /node_modules/, /.git*/"
